version: 0.2

env:
  shell: /bin/bash
  variables:
    ENV_VAR: DEV
  exported-variables:
    - VAR1
    - VAR2

phases:
  pre-build:
    commands:
      - cd $CODEBUILD_SRC_DIR_SourceArtifact2
      - ls -al
  build:
    commands:
      - echo $ENV_VAR
      - ls -al  # Primary source
      - cd $CODEBUILD_SRC_DIR
      - python test.py
      - cd $CODEBUILD_SRC_DIR_SourceArtifact2  # Access to 2nd source
      - ls -al
      - cd $CODEBUILD_SRC_DIR
      - cp $CODEBUILD_SRC_DIR_SourceArtifact2/* .
      - ls -al
      - python test2.py
      - echo $SOURCE1_DATE
      - echo $SOURCE1_BH
      - echo $SOURCE1_CMTID
      - echo $SOURCE1_CMTMSG
      - echo $SOURCE1_CON
      - echo $SOURCE1_REPO
      - echo $AWS_DEFAULT_REGION
      - echo $AWS_REGION
      - echo $CODEBUILD_BATCH_BUILD_IDENTIFIER
      - echo $CODEBUILD_BUILD_ARN
      - echo $CODEBUILD_BUILD_ID
      - echo $CODEBUILD_BUILD_IMAGE
      - echo $CODEBUILD_BUILD_NUMBER
      - echo $CODEBUILD_BUILD_SUCCEEDING
      - echo $CODEBUILD_INITIATOR
      - echo $CODEBUILD_KMS_KEY_ID
      - echo $CODEBUILD_LOG_PATH
      - echo $CODEBUILD_PUBLIC_BUILD_URL
      - echo $CODEBUILD_RESOLVED_SOURCE_VERSION
      - echo $CODEBUILD_SOURCE_REPO_URL
      - echo $CODEBUILD_SOURCE_VERSION
      - echo $CODEBUILD_SOURCE_VERSION_Source2
      - echo $CODEBUILD_START_TIME
      - echo $CODEBUILD_WEBHOOK_ACTOR_ACCOUNT_ID
      - echo $CODEBUILD_WEBHOOK_BASE_REF
      - echo $CODEBUILD_WEBHOOK_EVENT
      - echo $CODEBUILD_WEBHOOK_MERGE_COMMIT
      - echo $CODEBUILD_WEBHOOK_PREV_COMMIT
      - echo $CODEBUILD_WEBHOOK_HEAD_REF
      - echo $CODEBUILD_WEBHOOK_TRIGGER
      - echo $HOME
      - export VAR2='CustomVaraible2'
