version: 0.2

env:
  shell: /bin/bash
  variables:
    SOURCE1BH: $CODEBUILD_SOURCE_VERSION_SourceArtifact1
    SOURCE2BH: $CODEBUILD_SOURCE_VERSION_SourceArtifact2

phases:
  build:
    commands:
      - cd $CODEBUILD_SRC_DIR_SourceArtifact1
      - python test.py $SOURCE1BH
      - cd $CODEBUILD_SRC_DIR_SourceArtifact2
      - python test2.py $SOURCE2BH
